POST http://localhost:3005/login
Content-Type: application/json

{
    "memberid":"admin",
    "password":"123"
}

###
POST http://localhost:3005/register
Content-Type: application/json

{
    "memberid":"adm",
    "password":"123"
}

###
POST http://localhost:3005/newrecord
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJpZCI6ImFkbWluIiwiaWF0IjoxNjQ2NDYwNjIzfQ.e9qIU0EIJcu4VN5iI4u3ta_T0rejPkGLacrRePjr1EQ
Content-Type: application/json

{
    "memberid":"admin",
    "name":"sai",
    "date":"2022-02-16",
    "mobileNo":"1234",
    "BP":"12",
    "FBS":"123",
    "PPBS":"34",
    "RBS":"54",
    "HbA1C":"45",
    "Urea":"67",
    "Creatinine":"34",
    "Complaints":"no",
    "OthersignificantNotes":""
}

###
GET http://localhost:3005/showrecord
Authorization : BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJpZCI6ImFkbWluIiwiaWF0IjoxNjQ2MjE1MjgyfQ.DI0TfI_B0SNJ6oZdlhvZjjHYljkzVNChtmaaVvzVXU4